// web_pages.h — GENERATED.  Edit sources in web/ then run scripts/embed_web.py.
// Do not edit this file directly.
#pragma once

static const char WEB_PAGE_HOME[] = R"html(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>AMIDALA</title>
<style>
/* Amidala web UI — shared styles.
   Embed script inlines this into every page's <style> block.
   In dev mode (scripts/web_dev.py) it's served as a real file from /assets/common.css. */

*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

:root {
  --gold:   #ffe81f;
  --red:    #c00;
  --bg:     #000;
  --card:   #0a0a0a;
  --dim:    #555;
  --border: #ffe81f22;
}

body {
  background: var(--bg);
  color: var(--gold);
  font-family: 'Courier New', Courier, monospace;
  min-height: 100vh;
  font-size: 15px;
}

a {
  color: var(--gold);
  text-decoration: none;
}

button {
  cursor: pointer;
  font-family: inherit;
}

.hidden {
  display: none !important;
}

.toast {
  position: fixed;
  bottom: 1.5rem;
  left: 50%;
  transform: translateX(-50%);
  background: #111;
  border: 1px solid var(--gold);
  color: var(--gold);
  padding: .55rem 1.4rem;
  font-size: .78rem;
  letter-spacing: .08em;
  pointer-events: none;
  white-space: nowrap;
  animation: _tfi .15s ease, _tfo .3s 1.9s ease forwards;
  z-index: 9999;
}
.toast-err {
  border-color: var(--red);
  color: var(--red);
}
@keyframes _tfi {
  from { opacity: 0; transform: translateX(-50%) translateY(6px) }
  to   { opacity: 1; transform: translateX(-50%) translateY(0) }
}
@keyframes _tfo {
  from { opacity: 1 }
  to   { opacity: 0 }
}
</style>
<style>
header{text-align:center;padding:2rem 1rem 1.5rem;border-bottom:1px solid var(--border)}
.logo{font-size:clamp(1.6rem,6vw,2.8rem);letter-spacing:.4em;text-transform:uppercase}
.subtitle{color:var(--dim);font-size:.72rem;letter-spacing:.18em;margin-top:.35rem}
.build-strip{display:flex;flex-wrap:wrap;justify-content:center;border-bottom:1px solid var(--border)}
.bi{padding:.8rem 1.4rem;text-align:center;border-right:1px solid var(--border)}
.bi:last-child{border-right:none}
.bi .lbl{font-size:.58rem;color:var(--dim);text-transform:uppercase;letter-spacing:.15em}
.bi .val{font-size:.9rem;margin-top:.2rem}
.sh{text-align:center;color:var(--dim);font-size:.62rem;letter-spacing:.3em;text-transform:uppercase;padding:1.4rem 1rem .7rem}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:1px;background:var(--border);border:1px solid var(--border);max-width:840px;margin:0 auto 1.5rem}
.card{display:flex;flex-direction:column;align-items:center;justify-content:center;background:var(--bg);padding:1.4rem 1rem;text-align:center;min-height:90px;transition:background .1s;-webkit-tap-highlight-color:transparent}
.card:hover,.card:focus{background:#0e0e0e;outline:none}
.card:active{background:#141414}
.card .icon{font-size:1.5rem;margin-bottom:.5rem;line-height:1}
.card .name{font-size:.72rem;letter-spacing:.04em;line-height:1.35}
</style>
</head>
<body>
<header>
  <div class="logo">&#9670; AMIDALA &#9670;</div>
  <div class="subtitle" id="fwv">&#8212;</div>
</header>
<div class="build-strip">
  <div class="bi"><div class="lbl">Drive</div><div class="val" id="bi-dr">&#8212;</div></div>
  <div class="bi"><div class="lbl">Dome</div><div class="val" id="bi-do">&#8212;</div></div>
  <div class="bi"><div class="lbl">Audio</div><div class="val" id="bi-au">&#8212;</div></div>
  <div class="bi"><div class="lbl">Network</div><div class="val" id="bi-wi">&#8212;</div></div>
</div>
<div class="sh">&#9670;&#9670; Configuration &#9670;&#9670;</div>
<nav class="grid">
  <a class="card" href="/config/general"><div class="icon">&#9881;</div><div class="name">General</div></a>
  <a class="card" href="/config/audio"><div class="icon">&#9834;</div><div class="name">Audio</div></a>
  <a class="card" href="/config/dome"><div class="icon">&#8853;</div><div class="name">Dome Drive</div></a>
  <a class="card" href="/config/buttons"><div class="icon">&#9711;</div><div class="name">Buttons &amp; Gestures</div></a>
  <a class="card" href="/config/servos"><div class="icon">&#9699;</div><div class="name">Servos</div></a>
  <a class="card" href="/config/xbee"><div class="icon">&#9702;</div><div class="name">XBee</div></a>
  <a class="card" href="/config/serial-strings"><div class="icon">&#9166;</div><div class="name">Serial Strings</div></a>
  <a class="card" href="/config/rc-radio"><div class="icon">&#9526;</div><div class="name">RC Radio</div></a>
  <a class="card" href="/config/wifi"><div class="icon">&#10047;</div><div class="name">WiFi</div></a>
</nav>
<div class="sh">&#9670;&#9670; Tools &#9670;&#9670;</div>
<nav class="grid">
  <a class="card" href="/sequences"><div class="icon">&#9654;</div><div class="name">Sequences</div></a>
  <a class="card" href="/monitor"><div class="icon">&#9680;</div><div class="name">Serial Monitor</div></a>
  <a class="card" href="/update"><div class="icon">&#8679;</div><div class="name">Firmware Update</div></a>
</nav>
<script>
fetch('/api/info').then(function(r){return r.json();}).then(function(d){
  document.getElementById('fwv').textContent=d.firmware+' v'+d.version+' · '+d.date;
  document.getElementById('bi-dr').textContent=d.drive||'none';
  document.getElementById('bi-do').textContent=d.dome||'none';
  document.getElementById('bi-au').textContent=d.audio;
  document.getElementById('bi-wi').textContent=d.wifi_ssid;
}).catch(function(){document.getElementById('fwv').textContent='connection error';});
</script>
</body>
</html>
)html";

static const char WEB_PAGE_GENERAL[] = R"html(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>General Settings — AMIDALA</title>
<style>
/* Amidala web UI — shared styles.
   Embed script inlines this into every page's <style> block.
   In dev mode (scripts/web_dev.py) it's served as a real file from /assets/common.css. */

*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

:root {
  --gold:   #ffe81f;
  --red:    #c00;
  --bg:     #000;
  --card:   #0a0a0a;
  --dim:    #555;
  --border: #ffe81f22;
}

body {
  background: var(--bg);
  color: var(--gold);
  font-family: 'Courier New', Courier, monospace;
  min-height: 100vh;
  font-size: 15px;
}

a {
  color: var(--gold);
  text-decoration: none;
}

button {
  cursor: pointer;
  font-family: inherit;
}

.hidden {
  display: none !important;
}

.toast {
  position: fixed;
  bottom: 1.5rem;
  left: 50%;
  transform: translateX(-50%);
  background: #111;
  border: 1px solid var(--gold);
  color: var(--gold);
  padding: .55rem 1.4rem;
  font-size: .78rem;
  letter-spacing: .08em;
  pointer-events: none;
  white-space: nowrap;
  animation: _tfi .15s ease, _tfo .3s 1.9s ease forwards;
  z-index: 9999;
}
.toast-err {
  border-color: var(--red);
  color: var(--red);
}
@keyframes _tfi {
  from { opacity: 0; transform: translateX(-50%) translateY(6px) }
  to   { opacity: 1; transform: translateX(-50%) translateY(0) }
}
@keyframes _tfo {
  from { opacity: 1 }
  to   { opacity: 0 }
}
</style>
<style>
.page-header{display:flex;align-items:center;padding:.9rem 1rem;border-bottom:1px solid var(--border);gap:1rem}
.back{font-size:.8rem;color:var(--dim);letter-spacing:.1em;white-space:nowrap}
.back:hover{color:var(--gold)}
.page-title{flex:1;text-align:center;font-size:.9rem;letter-spacing:.25em;text-transform:uppercase}
main{max-width:660px;margin:0 auto;padding:1rem}
.section-label{font-size:.6rem;color:var(--dim);letter-spacing:.25em;text-transform:uppercase;padding:.5rem 0 .4rem;border-bottom:1px solid var(--border);margin-bottom:.2rem}
.row{display:flex;align-items:center;padding:.7rem .2rem;border-bottom:1px solid #0f0f0f;gap:.5rem}
.row-label{flex:1;font-size:.82rem;color:#ccc}
.rv{font-size:.82rem;color:var(--gold);min-width:60px;text-align:right}
.ri{min-width:90px}
.ri input,.ri select{width:100%;background:#111;border:1px solid var(--dim);color:var(--gold);padding:.3rem .5rem;font-family:inherit;font-size:.82rem}
.ri select option{background:#111}
.be,.bs,.bc{background:none;border:none;color:var(--gold);font-size:1rem;padding:.2rem .5rem;opacity:.6}
.be:hover,.bs:hover,.bc:hover{opacity:1}
.bc{color:var(--dim)}
#status{text-align:center;padding:2rem;color:var(--dim);font-size:.8rem;letter-spacing:.1em}
</style>
</head>
<body>
<div class="page-header">
  <a class="back" href="/">&#9664; Back</a>
  <div class="page-title">&#9670; General Settings &#9670;</div>
</div>
<main>
  <div id="status">LOADING&#8230;</div>
</main>
<script>
/* Amidala web UI — edit-in-place widget + shared config page helpers.
   Embed script inlines this into every config sub-page.
   In dev mode (scripts/web_dev.py) it's served as /assets/edit.js. */

// ------------------------------------------------------------------ toast ---

function showToast(msg, isErr) {
  var t = document.createElement('div');
  t.className = 'toast' + (isErr ? ' toast-err' : '');
  t.textContent = msg;
  document.body.appendChild(t);
  setTimeout(function() { if (t.parentNode) t.parentNode.removeChild(t); }, 2200);
}

// -------------------------------------------------------- edit-in-place -----

function startEdit(btn) {
  var row = btn.closest('.row');
  row.querySelector('.rv').hidden = true;
  row.querySelector('.ri').hidden = false;
  btn.hidden = true;
  row.querySelector('.bs').hidden = false;
  row.querySelector('.bc').hidden = false;
}

function doCancel(btn) {
  var row = btn.closest('.row');
  row.querySelector('.rv').hidden = false;
  row.querySelector('.ri').hidden = true;
  row.querySelector('.be').hidden = false;
  row.querySelector('.bs').hidden = true;
  btn.hidden = true;
}

async function doSave(btn) {
  var row = btn.closest('.row');
  var key = row.dataset.key;
  var inp = row.querySelector('input,select');
  var val = inp.value;
  var prev = btn.textContent;
  btn.textContent = '...';
  btn.disabled = true;
  try {
    var r = await fetch('/api/config', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: 'key=' + encodeURIComponent(key) + '&value=' + encodeURIComponent(val)
    });
    if (r.ok) {
      var dv = row.querySelector('.rv');
      var rt = row.dataset.type;
      if (rt === 'bool' || rt === 'select') {
        var sel = row.querySelector('select');
        dv.textContent = sel.options[sel.selectedIndex].text;
      } else if (rt === 'password') {
        dv.textContent = '••••••••';
      } else {
        dv.textContent = val;
      }
      doCancel(row.querySelector('.bc'));
      showToast('Saved');
    } else {
      showToast('Save failed: ' + await r.text(), true);
    }
  } catch(e) {
    showToast('Network error', true);
  }
  btn.textContent = prev;
  btn.disabled = false;
}

// ------------------------------------------------ schema-driven row builder --

function dispValue(s, val) {
  if (s.type === 'bool') return val === 'y' ? 'On' : 'Off';
  if (s.type === 'select') {
    var found = (s.options || []).find(function(op) { return op.v === String(val); });
    return found ? found.l : val;
  }
  if (s.type === 'password') return '••••••••';
  return String(val);
}

function buildInput(s, val) {
  if (s.type === 'bool') {
    return '<select>'
      + '<option value="y"' + (val === 'y' ? ' selected' : '') + '>On</option>'
      + '<option value="n"' + (val === 'n' ? ' selected' : '') + '>Off</option>'
      + '</select>';
  }
  if (s.type === 'select') {
    var opts = (s.options || []).map(function(op) {
      return '<option value="' + op.v + '"' + (String(val) === op.v ? ' selected' : '') + '>' + op.l + '</option>';
    }).join('');
    return '<select>' + opts + '</select>';
  }
  if (s.type === 'number') {
    return '<input type="number" value="' + val + '" min="' + (s.min || 0) + '" max="' + (s.max || 9999) + '">';
  }
  if (s.type === 'password') {
    return '<input type="password" value="' + val + '" maxlength="' + (s.maxlength || 64) + '">';
  }
  return '<input type="text" value="' + val + '"' + (s.maxlength ? ' maxlength="' + s.maxlength + '"' : '') + '>';
}

function buildRow(s, val) {
  var disp = dispValue(s, val);
  var note = s.note ? '<span style="font-size:.65rem;color:var(--dim);margin-left:.3rem">' + s.note + '</span>' : '';
  if (s.readOnly) {
    return '<div class="row" data-key="' + (s.key || '') + '" data-type="' + (s.type || 'text') + '">'
      + '<div class="row-label">' + s.label + '</div>'
      + '<div class="rv">' + disp + '</div>'
      + '</div>';
  }
  return '<div class="row" data-key="' + (s.key || '') + '" data-type="' + (s.type || 'text') + '">'
    + '<div class="row-label">' + s.label + '</div>'
    + '<div class="rv">' + disp + '</div>'
    + '<div class="ri" hidden><div style="display:flex;align-items:center">' + buildInput(s, val) + note + '</div></div>'
    + '<button class="be" onclick="startEdit(this)" title="Edit">&#9998;</button>'
    + '<button class="bs hidden" onclick="doSave(this)" title="Save">&#10003;</button>'
    + '<button class="bc hidden" onclick="doCancel(this)" title="Cancel">&#10005;</button>'
    + '</div>';
}

function buildPage(SCHEMA, endpoint) {
  fetch(endpoint)
    .then(function(r) { return r.json(); })
    .then(function(d) {
      var html = '';
      SCHEMA.forEach(function(s) {
        if (s.section) {
          html += '<div class="section-label">' + s.section + '</div>';
          return;
        }
        var val = (d[s.key] !== undefined) ? String(d[s.key]) : '?';
        html += buildRow(s, val);
      });
      document.querySelector('main').innerHTML = html;
    })
    .catch(function() {
      var el = document.getElementById('status');
      if (el) el.textContent = 'Failed to load settings.';
    });
}
</script>
<script>
var SCHEMA = [
  {section:'Sound'},
  {key:'volume',     label:'Volume',             type:'number', min:0,   max:100},
  {key:'startup',    label:'Startup Sound',      type:'bool'},
  {key:'rndon',      label:'Random Sounds',      type:'bool'},
  {key:'mindelay',   label:'Random Min Delay',   type:'number', min:0,   max:1000, note:'seconds'},
  {key:'maxdelay',   label:'Random Max Delay',   type:'number', min:0,   max:1000, note:'seconds'},
  {key:'ackon',      label:'Ack Sounds',         type:'bool'},
  {section:'Drive'},
  {key:'goslow',     label:'Start in Slow Mode', type:'bool'},
  {key:'mix12',      label:'Channel Mixing',     type:'bool'},
  {key:'auto',       label:'Autocorrect Gestures', type:'bool'},
  {section:'Serial'},
  {key:'serialbaud', label:'Baud Rate',          type:'number', min:300, max:115200},
  {key:'serialdelim',label:'Delimiter (ASCII)',  type:'number', min:0,   max:255},
  {key:'serialeol',  label:'EOL (ASCII)',         type:'number', min:0,   max:255},
  {section:'I²C'},
  {key:'myi2c',      label:"This Board's Address", type:'number', min:0, max:100}
];
buildPage(SCHEMA, '/api/config/general');
</script>
</body>
</html>
)html";

static const char WEB_PAGE_WIFI[] = R"html(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>WiFi — AMIDALA</title>
<style>
/* Amidala web UI — shared styles.
   Embed script inlines this into every page's <style> block.
   In dev mode (scripts/web_dev.py) it's served as a real file from /assets/common.css. */

*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

:root {
  --gold:   #ffe81f;
  --red:    #c00;
  --bg:     #000;
  --card:   #0a0a0a;
  --dim:    #555;
  --border: #ffe81f22;
}

body {
  background: var(--bg);
  color: var(--gold);
  font-family: 'Courier New', Courier, monospace;
  min-height: 100vh;
  font-size: 15px;
}

a {
  color: var(--gold);
  text-decoration: none;
}

button {
  cursor: pointer;
  font-family: inherit;
}

.hidden {
  display: none !important;
}

.toast {
  position: fixed;
  bottom: 1.5rem;
  left: 50%;
  transform: translateX(-50%);
  background: #111;
  border: 1px solid var(--gold);
  color: var(--gold);
  padding: .55rem 1.4rem;
  font-size: .78rem;
  letter-spacing: .08em;
  pointer-events: none;
  white-space: nowrap;
  animation: _tfi .15s ease, _tfo .3s 1.9s ease forwards;
  z-index: 9999;
}
.toast-err {
  border-color: var(--red);
  color: var(--red);
}
@keyframes _tfi {
  from { opacity: 0; transform: translateX(-50%) translateY(6px) }
  to   { opacity: 1; transform: translateX(-50%) translateY(0) }
}
@keyframes _tfo {
  from { opacity: 1 }
  to   { opacity: 0 }
}
</style>
<style>
.page-header{display:flex;align-items:center;padding:.9rem 1rem;border-bottom:1px solid var(--border);gap:1rem}
.back{font-size:.8rem;color:var(--dim);letter-spacing:.1em;white-space:nowrap}
.back:hover{color:var(--gold)}
.page-title{flex:1;text-align:center;font-size:.9rem;letter-spacing:.25em;text-transform:uppercase}
main{max-width:660px;margin:0 auto;padding:1rem}
.section-label{font-size:.6rem;color:var(--dim);letter-spacing:.25em;text-transform:uppercase;padding:.5rem 0 .4rem;border-bottom:1px solid var(--border);margin-bottom:.2rem}
.row{display:flex;align-items:center;padding:.7rem .2rem;border-bottom:1px solid #0f0f0f;gap:.5rem}
.row-label{flex:1;font-size:.82rem;color:#ccc}
.rv{font-size:.82rem;color:var(--gold);min-width:60px;text-align:right}
.ri{min-width:90px}
.ri input,.ri select{width:100%;background:#111;border:1px solid var(--dim);color:var(--gold);padding:.3rem .5rem;font-family:inherit;font-size:.82rem}
.ri select option{background:#111}
.be,.bs,.bc{background:none;border:none;color:var(--gold);font-size:1rem;padding:.2rem .5rem;opacity:.6}
.be:hover,.bs:hover,.bc:hover{opacity:1}
.bc{color:var(--dim)}
#status{text-align:center;padding:2rem;color:var(--dim);font-size:.8rem;letter-spacing:.1em}
</style>
</head>
<body>
<div class="page-header">
  <a class="back" href="/">&#9664; Back</a>
  <div class="page-title">&#9670; WiFi &#9670;</div>
</div>
<main>
  <div id="status">LOADING&#8230;</div>
</main>
<script>
/* Amidala web UI — edit-in-place widget + shared config page helpers.
   Embed script inlines this into every config sub-page.
   In dev mode (scripts/web_dev.py) it's served as /assets/edit.js. */

// ------------------------------------------------------------------ toast ---

function showToast(msg, isErr) {
  var t = document.createElement('div');
  t.className = 'toast' + (isErr ? ' toast-err' : '');
  t.textContent = msg;
  document.body.appendChild(t);
  setTimeout(function() { if (t.parentNode) t.parentNode.removeChild(t); }, 2200);
}

// -------------------------------------------------------- edit-in-place -----

function startEdit(btn) {
  var row = btn.closest('.row');
  row.querySelector('.rv').hidden = true;
  row.querySelector('.ri').hidden = false;
  btn.hidden = true;
  row.querySelector('.bs').hidden = false;
  row.querySelector('.bc').hidden = false;
}

function doCancel(btn) {
  var row = btn.closest('.row');
  row.querySelector('.rv').hidden = false;
  row.querySelector('.ri').hidden = true;
  row.querySelector('.be').hidden = false;
  row.querySelector('.bs').hidden = true;
  btn.hidden = true;
}

async function doSave(btn) {
  var row = btn.closest('.row');
  var key = row.dataset.key;
  var inp = row.querySelector('input,select');
  var val = inp.value;
  var prev = btn.textContent;
  btn.textContent = '...';
  btn.disabled = true;
  try {
    var r = await fetch('/api/config', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: 'key=' + encodeURIComponent(key) + '&value=' + encodeURIComponent(val)
    });
    if (r.ok) {
      var dv = row.querySelector('.rv');
      var rt = row.dataset.type;
      if (rt === 'bool' || rt === 'select') {
        var sel = row.querySelector('select');
        dv.textContent = sel.options[sel.selectedIndex].text;
      } else if (rt === 'password') {
        dv.textContent = '••••••••';
      } else {
        dv.textContent = val;
      }
      doCancel(row.querySelector('.bc'));
      showToast('Saved');
    } else {
      showToast('Save failed: ' + await r.text(), true);
    }
  } catch(e) {
    showToast('Network error', true);
  }
  btn.textContent = prev;
  btn.disabled = false;
}

// ------------------------------------------------ schema-driven row builder --

function dispValue(s, val) {
  if (s.type === 'bool') return val === 'y' ? 'On' : 'Off';
  if (s.type === 'select') {
    var found = (s.options || []).find(function(op) { return op.v === String(val); });
    return found ? found.l : val;
  }
  if (s.type === 'password') return '••••••••';
  return String(val);
}

function buildInput(s, val) {
  if (s.type === 'bool') {
    return '<select>'
      + '<option value="y"' + (val === 'y' ? ' selected' : '') + '>On</option>'
      + '<option value="n"' + (val === 'n' ? ' selected' : '') + '>Off</option>'
      + '</select>';
  }
  if (s.type === 'select') {
    var opts = (s.options || []).map(function(op) {
      return '<option value="' + op.v + '"' + (String(val) === op.v ? ' selected' : '') + '>' + op.l + '</option>';
    }).join('');
    return '<select>' + opts + '</select>';
  }
  if (s.type === 'number') {
    return '<input type="number" value="' + val + '" min="' + (s.min || 0) + '" max="' + (s.max || 9999) + '">';
  }
  if (s.type === 'password') {
    return '<input type="password" value="' + val + '" maxlength="' + (s.maxlength || 64) + '">';
  }
  return '<input type="text" value="' + val + '"' + (s.maxlength ? ' maxlength="' + s.maxlength + '"' : '') + '>';
}

function buildRow(s, val) {
  var disp = dispValue(s, val);
  var note = s.note ? '<span style="font-size:.65rem;color:var(--dim);margin-left:.3rem">' + s.note + '</span>' : '';
  if (s.readOnly) {
    return '<div class="row" data-key="' + (s.key || '') + '" data-type="' + (s.type || 'text') + '">'
      + '<div class="row-label">' + s.label + '</div>'
      + '<div class="rv">' + disp + '</div>'
      + '</div>';
  }
  return '<div class="row" data-key="' + (s.key || '') + '" data-type="' + (s.type || 'text') + '">'
    + '<div class="row-label">' + s.label + '</div>'
    + '<div class="rv">' + disp + '</div>'
    + '<div class="ri" hidden><div style="display:flex;align-items:center">' + buildInput(s, val) + note + '</div></div>'
    + '<button class="be" onclick="startEdit(this)" title="Edit">&#9998;</button>'
    + '<button class="bs hidden" onclick="doSave(this)" title="Save">&#10003;</button>'
    + '<button class="bc hidden" onclick="doCancel(this)" title="Cancel">&#10005;</button>'
    + '</div>';
}

function buildPage(SCHEMA, endpoint) {
  fetch(endpoint)
    .then(function(r) { return r.json(); })
    .then(function(d) {
      var html = '';
      SCHEMA.forEach(function(s) {
        if (s.section) {
          html += '<div class="section-label">' + s.section + '</div>';
          return;
        }
        var val = (d[s.key] !== undefined) ? String(d[s.key]) : '?';
        html += buildRow(s, val);
      });
      document.querySelector('main').innerHTML = html;
    })
    .catch(function() {
      var el = document.getElementById('status');
      if (el) el.textContent = 'Failed to load settings.';
    });
}
</script>
<script>
var SCHEMA = [
  {section:'Access Point'},
  {key:'wifion',       label:'Enable WiFi AP', type:'bool'},
  {key:'wifissid',     label:'SSID',           type:'text',     maxlength:32, note:'max 32 chars'},
  {key:'wifipassword', label:'Password',       type:'password', maxlength:64, note:'min 8 chars'}
];
buildPage(SCHEMA, '/api/config/wifi');
</script>
</body>
</html>
)html";

static const char WEB_PAGE_XBEE[] = R"html(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>XBee — AMIDALA</title>
<style>
/* Amidala web UI — shared styles.
   Embed script inlines this into every page's <style> block.
   In dev mode (scripts/web_dev.py) it's served as a real file from /assets/common.css. */

*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

:root {
  --gold:   #ffe81f;
  --red:    #c00;
  --bg:     #000;
  --card:   #0a0a0a;
  --dim:    #555;
  --border: #ffe81f22;
}

body {
  background: var(--bg);
  color: var(--gold);
  font-family: 'Courier New', Courier, monospace;
  min-height: 100vh;
  font-size: 15px;
}

a {
  color: var(--gold);
  text-decoration: none;
}

button {
  cursor: pointer;
  font-family: inherit;
}

.hidden {
  display: none !important;
}

.toast {
  position: fixed;
  bottom: 1.5rem;
  left: 50%;
  transform: translateX(-50%);
  background: #111;
  border: 1px solid var(--gold);
  color: var(--gold);
  padding: .55rem 1.4rem;
  font-size: .78rem;
  letter-spacing: .08em;
  pointer-events: none;
  white-space: nowrap;
  animation: _tfi .15s ease, _tfo .3s 1.9s ease forwards;
  z-index: 9999;
}
.toast-err {
  border-color: var(--red);
  color: var(--red);
}
@keyframes _tfi {
  from { opacity: 0; transform: translateX(-50%) translateY(6px) }
  to   { opacity: 1; transform: translateX(-50%) translateY(0) }
}
@keyframes _tfo {
  from { opacity: 1 }
  to   { opacity: 0 }
}
</style>
<style>
.page-header{display:flex;align-items:center;padding:.9rem 1rem;border-bottom:1px solid var(--border);gap:1rem}
.back{font-size:.8rem;color:var(--dim);letter-spacing:.1em;white-space:nowrap}
.back:hover{color:var(--gold)}
.page-title{flex:1;text-align:center;font-size:.9rem;letter-spacing:.25em;text-transform:uppercase}
main{max-width:660px;margin:0 auto;padding:1rem}
.section-label{font-size:.6rem;color:var(--dim);letter-spacing:.25em;text-transform:uppercase;padding:.5rem 0 .4rem;border-bottom:1px solid var(--border);margin-bottom:.2rem}
.row{display:flex;align-items:center;padding:.7rem .2rem;border-bottom:1px solid #0f0f0f;gap:.5rem}
.row-label{flex:1;font-size:.82rem;color:#ccc}
.rv{font-size:.82rem;color:var(--gold);min-width:60px;text-align:right}
.ri{min-width:90px}
.ri input,.ri select{width:100%;background:#111;border:1px solid var(--dim);color:var(--gold);padding:.3rem .5rem;font-family:inherit;font-size:.82rem}
.ri select option{background:#111}
.be,.bs,.bc{background:none;border:none;color:var(--gold);font-size:1rem;padding:.2rem .5rem;opacity:.6}
.be:hover,.bs:hover,.bc:hover{opacity:1}
.bc{color:var(--dim)}
#status{text-align:center;padding:2rem;color:var(--dim);font-size:.8rem;letter-spacing:.1em}
</style>
</head>
<body>
<div class="page-header">
  <a class="back" href="/">&#9664; Back</a>
  <div class="page-title">&#9670; XBee &#9670;</div>
</div>
<main>
  <div id="status">LOADING&#8230;</div>
</main>
<script>
/* Amidala web UI — edit-in-place widget + shared config page helpers.
   Embed script inlines this into every config sub-page.
   In dev mode (scripts/web_dev.py) it's served as /assets/edit.js. */

// ------------------------------------------------------------------ toast ---

function showToast(msg, isErr) {
  var t = document.createElement('div');
  t.className = 'toast' + (isErr ? ' toast-err' : '');
  t.textContent = msg;
  document.body.appendChild(t);
  setTimeout(function() { if (t.parentNode) t.parentNode.removeChild(t); }, 2200);
}

// -------------------------------------------------------- edit-in-place -----

function startEdit(btn) {
  var row = btn.closest('.row');
  row.querySelector('.rv').hidden = true;
  row.querySelector('.ri').hidden = false;
  btn.hidden = true;
  row.querySelector('.bs').hidden = false;
  row.querySelector('.bc').hidden = false;
}

function doCancel(btn) {
  var row = btn.closest('.row');
  row.querySelector('.rv').hidden = false;
  row.querySelector('.ri').hidden = true;
  row.querySelector('.be').hidden = false;
  row.querySelector('.bs').hidden = true;
  btn.hidden = true;
}

async function doSave(btn) {
  var row = btn.closest('.row');
  var key = row.dataset.key;
  var inp = row.querySelector('input,select');
  var val = inp.value;
  var prev = btn.textContent;
  btn.textContent = '...';
  btn.disabled = true;
  try {
    var r = await fetch('/api/config', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: 'key=' + encodeURIComponent(key) + '&value=' + encodeURIComponent(val)
    });
    if (r.ok) {
      var dv = row.querySelector('.rv');
      var rt = row.dataset.type;
      if (rt === 'bool' || rt === 'select') {
        var sel = row.querySelector('select');
        dv.textContent = sel.options[sel.selectedIndex].text;
      } else if (rt === 'password') {
        dv.textContent = '••••••••';
      } else {
        dv.textContent = val;
      }
      doCancel(row.querySelector('.bc'));
      showToast('Saved');
    } else {
      showToast('Save failed: ' + await r.text(), true);
    }
  } catch(e) {
    showToast('Network error', true);
  }
  btn.textContent = prev;
  btn.disabled = false;
}

// ------------------------------------------------ schema-driven row builder --

function dispValue(s, val) {
  if (s.type === 'bool') return val === 'y' ? 'On' : 'Off';
  if (s.type === 'select') {
    var found = (s.options || []).find(function(op) { return op.v === String(val); });
    return found ? found.l : val;
  }
  if (s.type === 'password') return '••••••••';
  return String(val);
}

function buildInput(s, val) {
  if (s.type === 'bool') {
    return '<select>'
      + '<option value="y"' + (val === 'y' ? ' selected' : '') + '>On</option>'
      + '<option value="n"' + (val === 'n' ? ' selected' : '') + '>Off</option>'
      + '</select>';
  }
  if (s.type === 'select') {
    var opts = (s.options || []).map(function(op) {
      return '<option value="' + op.v + '"' + (String(val) === op.v ? ' selected' : '') + '>' + op.l + '</option>';
    }).join('');
    return '<select>' + opts + '</select>';
  }
  if (s.type === 'number') {
    return '<input type="number" value="' + val + '" min="' + (s.min || 0) + '" max="' + (s.max || 9999) + '">';
  }
  if (s.type === 'password') {
    return '<input type="password" value="' + val + '" maxlength="' + (s.maxlength || 64) + '">';
  }
  return '<input type="text" value="' + val + '"' + (s.maxlength ? ' maxlength="' + s.maxlength + '"' : '') + '>';
}

function buildRow(s, val) {
  var disp = dispValue(s, val);
  var note = s.note ? '<span style="font-size:.65rem;color:var(--dim);margin-left:.3rem">' + s.note + '</span>' : '';
  if (s.readOnly) {
    return '<div class="row" data-key="' + (s.key || '') + '" data-type="' + (s.type || 'text') + '">'
      + '<div class="row-label">' + s.label + '</div>'
      + '<div class="rv">' + disp + '</div>'
      + '</div>';
  }
  return '<div class="row" data-key="' + (s.key || '') + '" data-type="' + (s.type || 'text') + '">'
    + '<div class="row-label">' + s.label + '</div>'
    + '<div class="rv">' + disp + '</div>'
    + '<div class="ri" hidden><div style="display:flex;align-items:center">' + buildInput(s, val) + note + '</div></div>'
    + '<button class="be" onclick="startEdit(this)" title="Edit">&#9998;</button>'
    + '<button class="bs hidden" onclick="doSave(this)" title="Save">&#10003;</button>'
    + '<button class="bc hidden" onclick="doCancel(this)" title="Cancel">&#10005;</button>'
    + '</div>';
}

function buildPage(SCHEMA, endpoint) {
  fetch(endpoint)
    .then(function(r) { return r.json(); })
    .then(function(d) {
      var html = '';
      SCHEMA.forEach(function(s) {
        if (s.section) {
          html += '<div class="section-label">' + s.section + '</div>';
          return;
        }
        var val = (d[s.key] !== undefined) ? String(d[s.key]) : '?';
        html += buildRow(s, val);
      });
      document.querySelector('main').innerHTML = html;
    })
    .catch(function() {
      var el = document.getElementById('status');
      if (el) el.textContent = 'Failed to load settings.';
    });
}
</script>
<script>
var SCHEMA = [
  {section:'Remote Addresses (32-bit hex)'},
  {key:'xbr', label:'Drive Remote', type:'hex', note:'lower 32 bits of XBee address'},
  {key:'xbl', label:'Dome Remote',  type:'hex', note:'lower 32 bits of XBee address'}
];
buildPage(SCHEMA, '/api/config/xbee');
</script>
</body>
</html>
)html";

static const char WEB_PAGE_AUDIO[] = R"html(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Audio — AMIDALA</title>
<style>
/* Amidala web UI — shared styles.
   Embed script inlines this into every page's <style> block.
   In dev mode (scripts/web_dev.py) it's served as a real file from /assets/common.css. */

*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

:root {
  --gold:   #ffe81f;
  --red:    #c00;
  --bg:     #000;
  --card:   #0a0a0a;
  --dim:    #555;
  --border: #ffe81f22;
}

body {
  background: var(--bg);
  color: var(--gold);
  font-family: 'Courier New', Courier, monospace;
  min-height: 100vh;
  font-size: 15px;
}

a {
  color: var(--gold);
  text-decoration: none;
}

button {
  cursor: pointer;
  font-family: inherit;
}

.hidden {
  display: none !important;
}

.toast {
  position: fixed;
  bottom: 1.5rem;
  left: 50%;
  transform: translateX(-50%);
  background: #111;
  border: 1px solid var(--gold);
  color: var(--gold);
  padding: .55rem 1.4rem;
  font-size: .78rem;
  letter-spacing: .08em;
  pointer-events: none;
  white-space: nowrap;
  animation: _tfi .15s ease, _tfo .3s 1.9s ease forwards;
  z-index: 9999;
}
.toast-err {
  border-color: var(--red);
  color: var(--red);
}
@keyframes _tfi {
  from { opacity: 0; transform: translateX(-50%) translateY(6px) }
  to   { opacity: 1; transform: translateX(-50%) translateY(0) }
}
@keyframes _tfo {
  from { opacity: 1 }
  to   { opacity: 0 }
}
</style>
<style>
.page-header{display:flex;align-items:center;padding:.9rem 1rem;border-bottom:1px solid var(--border);gap:1rem}
.back{font-size:.8rem;color:var(--dim);letter-spacing:.1em;white-space:nowrap}
.back:hover{color:var(--gold)}
.page-title{flex:1;text-align:center;font-size:.9rem;letter-spacing:.25em;text-transform:uppercase}
main{max-width:660px;margin:0 auto;padding:1rem}
.section-label{font-size:.6rem;color:var(--dim);letter-spacing:.25em;text-transform:uppercase;padding:.5rem 0 .4rem;border-bottom:1px solid var(--border);margin-bottom:.2rem}
.row{display:flex;align-items:center;padding:.7rem .2rem;border-bottom:1px solid #0f0f0f;gap:.5rem}
.row-label{flex:1;font-size:.82rem;color:#ccc}
.rv{font-size:.82rem;color:var(--gold);min-width:60px;text-align:right}
.ri{min-width:90px}
.ri input,.ri select{width:100%;background:#111;border:1px solid var(--dim);color:var(--gold);padding:.3rem .5rem;font-family:inherit;font-size:.82rem}
.ri select option{background:#111}
.be,.bs,.bc{background:none;border:none;color:var(--gold);font-size:1rem;padding:.2rem .5rem;opacity:.6}
.be:hover,.bs:hover,.bc:hover{opacity:1}
.bc{color:var(--dim)}
#status{text-align:center;padding:2rem;color:var(--dim);font-size:.8rem;letter-spacing:.1em}
</style>
</head>
<body>
<div class="page-header">
  <a class="back" href="/">&#9664; Back</a>
  <div class="page-title">&#9670; Audio &#9670;</div>
</div>
<main>
  <div id="status">LOADING&#8230;</div>
</main>
<script>
/* Amidala web UI — edit-in-place widget + shared config page helpers.
   Embed script inlines this into every config sub-page.
   In dev mode (scripts/web_dev.py) it's served as /assets/edit.js. */

// ------------------------------------------------------------------ toast ---

function showToast(msg, isErr) {
  var t = document.createElement('div');
  t.className = 'toast' + (isErr ? ' toast-err' : '');
  t.textContent = msg;
  document.body.appendChild(t);
  setTimeout(function() { if (t.parentNode) t.parentNode.removeChild(t); }, 2200);
}

// -------------------------------------------------------- edit-in-place -----

function startEdit(btn) {
  var row = btn.closest('.row');
  row.querySelector('.rv').hidden = true;
  row.querySelector('.ri').hidden = false;
  btn.hidden = true;
  row.querySelector('.bs').hidden = false;
  row.querySelector('.bc').hidden = false;
}

function doCancel(btn) {
  var row = btn.closest('.row');
  row.querySelector('.rv').hidden = false;
  row.querySelector('.ri').hidden = true;
  row.querySelector('.be').hidden = false;
  row.querySelector('.bs').hidden = true;
  btn.hidden = true;
}

async function doSave(btn) {
  var row = btn.closest('.row');
  var key = row.dataset.key;
  var inp = row.querySelector('input,select');
  var val = inp.value;
  var prev = btn.textContent;
  btn.textContent = '...';
  btn.disabled = true;
  try {
    var r = await fetch('/api/config', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: 'key=' + encodeURIComponent(key) + '&value=' + encodeURIComponent(val)
    });
    if (r.ok) {
      var dv = row.querySelector('.rv');
      var rt = row.dataset.type;
      if (rt === 'bool' || rt === 'select') {
        var sel = row.querySelector('select');
        dv.textContent = sel.options[sel.selectedIndex].text;
      } else if (rt === 'password') {
        dv.textContent = '••••••••';
      } else {
        dv.textContent = val;
      }
      doCancel(row.querySelector('.bc'));
      showToast('Saved');
    } else {
      showToast('Save failed: ' + await r.text(), true);
    }
  } catch(e) {
    showToast('Network error', true);
  }
  btn.textContent = prev;
  btn.disabled = false;
}

// ------------------------------------------------ schema-driven row builder --

function dispValue(s, val) {
  if (s.type === 'bool') return val === 'y' ? 'On' : 'Off';
  if (s.type === 'select') {
    var found = (s.options || []).find(function(op) { return op.v === String(val); });
    return found ? found.l : val;
  }
  if (s.type === 'password') return '••••••••';
  return String(val);
}

function buildInput(s, val) {
  if (s.type === 'bool') {
    return '<select>'
      + '<option value="y"' + (val === 'y' ? ' selected' : '') + '>On</option>'
      + '<option value="n"' + (val === 'n' ? ' selected' : '') + '>Off</option>'
      + '</select>';
  }
  if (s.type === 'select') {
    var opts = (s.options || []).map(function(op) {
      return '<option value="' + op.v + '"' + (String(val) === op.v ? ' selected' : '') + '>' + op.l + '</option>';
    }).join('');
    return '<select>' + opts + '</select>';
  }
  if (s.type === 'number') {
    return '<input type="number" value="' + val + '" min="' + (s.min || 0) + '" max="' + (s.max || 9999) + '">';
  }
  if (s.type === 'password') {
    return '<input type="password" value="' + val + '" maxlength="' + (s.maxlength || 64) + '">';
  }
  return '<input type="text" value="' + val + '"' + (s.maxlength ? ' maxlength="' + s.maxlength + '"' : '') + '>';
}

function buildRow(s, val) {
  var disp = dispValue(s, val);
  var note = s.note ? '<span style="font-size:.65rem;color:var(--dim);margin-left:.3rem">' + s.note + '</span>' : '';
  if (s.readOnly) {
    return '<div class="row" data-key="' + (s.key || '') + '" data-type="' + (s.type || 'text') + '">'
      + '<div class="row-label">' + s.label + '</div>'
      + '<div class="rv">' + disp + '</div>'
      + '</div>';
  }
  return '<div class="row" data-key="' + (s.key || '') + '" data-type="' + (s.type || 'text') + '">'
    + '<div class="row-label">' + s.label + '</div>'
    + '<div class="rv">' + disp + '</div>'
    + '<div class="ri" hidden><div style="display:flex;align-items:center">' + buildInput(s, val) + note + '</div></div>'
    + '<button class="be" onclick="startEdit(this)" title="Edit">&#9998;</button>'
    + '<button class="bs hidden" onclick="doSave(this)" title="Save">&#10003;</button>'
    + '<button class="bc hidden" onclick="doCancel(this)" title="Cancel">&#10005;</button>'
    + '</div>';
}

function buildPage(SCHEMA, endpoint) {
  fetch(endpoint)
    .then(function(r) { return r.json(); })
    .then(function(d) {
      var html = '';
      SCHEMA.forEach(function(s) {
        if (s.section) {
          html += '<div class="section-label">' + s.section + '</div>';
          return;
        }
        var val = (d[s.key] !== undefined) ? String(d[s.key]) : '?';
        html += buildRow(s, val);
      });
      document.querySelector('main').innerHTML = html;
    })
    .catch(function() {
      var el = document.getElementById('status');
      if (el) el.textContent = 'Failed to load settings.';
    });
}
</script>
<script>
var _emo = [{v:'0',l:'Happy'},{v:'1',l:'Sad'},{v:'2',l:'Mad'},{v:'3',l:'Scared'},{v:'4',l:'Overload'}];
var _lvl = [{v:'0',l:'Moderate'},{v:'1',l:'Strong'}];
var _whl = [{v:'0',l:'Global (all)'},{v:'1',l:'Voice only'},{v:'2',l:'Ch A only'},{v:'3',l:'Ch B only'}];
var _awl = [{v:'0',l:'Same as wheel'},{v:'1',l:'Voice only'},{v:'2',l:'Ch A only'},{v:'3',l:'Ch B only'}];
var SCHEMA = [
  {section:'Hardware'},
  {key:'audiohw',        label:'Audio Board',        readOnly:true},
  {section:'Volume'},
  {key:'volumeChA',      label:'Channel A Volume',   type:'number', min:0, max:100},
  {key:'volumeChB',      label:'Channel B Volume',   type:'number', min:0, max:100},
  {key:'volumewheel',    label:'Volume Wheel',       type:'select', options:_whl},
  {key:'altvolumewheel', label:'Alt+Wheel',          type:'select', options:_awl},
  {section:'Startup Emote'},
  {key:'startupem',  label:'Emotion', type:'select', options:_emo},
  {key:'startuplvl', label:'Level',   type:'select', options:_lvl},
  {section:'Ack Emote'},
  {key:'ackem',  label:'Emotion', type:'select', options:_emo},
  {key:'acklvl', label:'Level',   type:'select', options:_lvl}
];
buildPage(SCHEMA, '/api/config/audio');
</script>
</body>
</html>
)html";

static const char WEB_PAGE_RC_RADIO[] = R"html(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>RC Radio — AMIDALA</title>
<style>
/* Amidala web UI — shared styles.
   Embed script inlines this into every page's <style> block.
   In dev mode (scripts/web_dev.py) it's served as a real file from /assets/common.css. */

*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

:root {
  --gold:   #ffe81f;
  --red:    #c00;
  --bg:     #000;
  --card:   #0a0a0a;
  --dim:    #555;
  --border: #ffe81f22;
}

body {
  background: var(--bg);
  color: var(--gold);
  font-family: 'Courier New', Courier, monospace;
  min-height: 100vh;
  font-size: 15px;
}

a {
  color: var(--gold);
  text-decoration: none;
}

button {
  cursor: pointer;
  font-family: inherit;
}

.hidden {
  display: none !important;
}

.toast {
  position: fixed;
  bottom: 1.5rem;
  left: 50%;
  transform: translateX(-50%);
  background: #111;
  border: 1px solid var(--gold);
  color: var(--gold);
  padding: .55rem 1.4rem;
  font-size: .78rem;
  letter-spacing: .08em;
  pointer-events: none;
  white-space: nowrap;
  animation: _tfi .15s ease, _tfo .3s 1.9s ease forwards;
  z-index: 9999;
}
.toast-err {
  border-color: var(--red);
  color: var(--red);
}
@keyframes _tfi {
  from { opacity: 0; transform: translateX(-50%) translateY(6px) }
  to   { opacity: 1; transform: translateX(-50%) translateY(0) }
}
@keyframes _tfo {
  from { opacity: 1 }
  to   { opacity: 0 }
}
</style>
<style>
.page-header{display:flex;align-items:center;padding:.9rem 1rem;border-bottom:1px solid var(--border);gap:1rem}
.back{font-size:.8rem;color:var(--dim);letter-spacing:.1em;white-space:nowrap}
.back:hover{color:var(--gold)}
.page-title{flex:1;text-align:center;font-size:.9rem;letter-spacing:.25em;text-transform:uppercase}
main{max-width:660px;margin:0 auto;padding:1rem}
.section-label{font-size:.6rem;color:var(--dim);letter-spacing:.25em;text-transform:uppercase;padding:.5rem 0 .4rem;border-bottom:1px solid var(--border);margin-bottom:.2rem}
.row{display:flex;align-items:center;padding:.7rem .2rem;border-bottom:1px solid #0f0f0f;gap:.5rem}
.row-label{flex:1;font-size:.82rem;color:#ccc}
.rv{font-size:.82rem;color:var(--gold);min-width:60px;text-align:right}
.ri{min-width:90px}
.ri input,.ri select{width:100%;background:#111;border:1px solid var(--dim);color:var(--gold);padding:.3rem .5rem;font-family:inherit;font-size:.82rem}
.ri select option{background:#111}
.be,.bs,.bc{background:none;border:none;color:var(--gold);font-size:1rem;padding:.2rem .5rem;opacity:.6}
.be:hover,.bs:hover,.bc:hover{opacity:1}
.bc{color:var(--dim)}
#status{text-align:center;padding:2rem;color:var(--dim);font-size:.8rem;letter-spacing:.1em}
</style>
</head>
<body>
<div class="page-header">
  <a class="back" href="/">&#9664; Back</a>
  <div class="page-title">&#9670; RC Radio &#9670;</div>
</div>
<main>
  <div id="status">LOADING&#8230;</div>
</main>
<script>
/* Amidala web UI — edit-in-place widget + shared config page helpers.
   Embed script inlines this into every config sub-page.
   In dev mode (scripts/web_dev.py) it's served as /assets/edit.js. */

// ------------------------------------------------------------------ toast ---

function showToast(msg, isErr) {
  var t = document.createElement('div');
  t.className = 'toast' + (isErr ? ' toast-err' : '');
  t.textContent = msg;
  document.body.appendChild(t);
  setTimeout(function() { if (t.parentNode) t.parentNode.removeChild(t); }, 2200);
}

// -------------------------------------------------------- edit-in-place -----

function startEdit(btn) {
  var row = btn.closest('.row');
  row.querySelector('.rv').hidden = true;
  row.querySelector('.ri').hidden = false;
  btn.hidden = true;
  row.querySelector('.bs').hidden = false;
  row.querySelector('.bc').hidden = false;
}

function doCancel(btn) {
  var row = btn.closest('.row');
  row.querySelector('.rv').hidden = false;
  row.querySelector('.ri').hidden = true;
  row.querySelector('.be').hidden = false;
  row.querySelector('.bs').hidden = true;
  btn.hidden = true;
}

async function doSave(btn) {
  var row = btn.closest('.row');
  var key = row.dataset.key;
  var inp = row.querySelector('input,select');
  var val = inp.value;
  var prev = btn.textContent;
  btn.textContent = '...';
  btn.disabled = true;
  try {
    var r = await fetch('/api/config', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: 'key=' + encodeURIComponent(key) + '&value=' + encodeURIComponent(val)
    });
    if (r.ok) {
      var dv = row.querySelector('.rv');
      var rt = row.dataset.type;
      if (rt === 'bool' || rt === 'select') {
        var sel = row.querySelector('select');
        dv.textContent = sel.options[sel.selectedIndex].text;
      } else if (rt === 'password') {
        dv.textContent = '••••••••';
      } else {
        dv.textContent = val;
      }
      doCancel(row.querySelector('.bc'));
      showToast('Saved');
    } else {
      showToast('Save failed: ' + await r.text(), true);
    }
  } catch(e) {
    showToast('Network error', true);
  }
  btn.textContent = prev;
  btn.disabled = false;
}

// ------------------------------------------------ schema-driven row builder --

function dispValue(s, val) {
  if (s.type === 'bool') return val === 'y' ? 'On' : 'Off';
  if (s.type === 'select') {
    var found = (s.options || []).find(function(op) { return op.v === String(val); });
    return found ? found.l : val;
  }
  if (s.type === 'password') return '••••••••';
  return String(val);
}

function buildInput(s, val) {
  if (s.type === 'bool') {
    return '<select>'
      + '<option value="y"' + (val === 'y' ? ' selected' : '') + '>On</option>'
      + '<option value="n"' + (val === 'n' ? ' selected' : '') + '>Off</option>'
      + '</select>';
  }
  if (s.type === 'select') {
    var opts = (s.options || []).map(function(op) {
      return '<option value="' + op.v + '"' + (String(val) === op.v ? ' selected' : '') + '>' + op.l + '</option>';
    }).join('');
    return '<select>' + opts + '</select>';
  }
  if (s.type === 'number') {
    return '<input type="number" value="' + val + '" min="' + (s.min || 0) + '" max="' + (s.max || 9999) + '">';
  }
  if (s.type === 'password') {
    return '<input type="password" value="' + val + '" maxlength="' + (s.maxlength || 64) + '">';
  }
  return '<input type="text" value="' + val + '"' + (s.maxlength ? ' maxlength="' + s.maxlength + '"' : '') + '>';
}

function buildRow(s, val) {
  var disp = dispValue(s, val);
  var note = s.note ? '<span style="font-size:.65rem;color:var(--dim);margin-left:.3rem">' + s.note + '</span>' : '';
  if (s.readOnly) {
    return '<div class="row" data-key="' + (s.key || '') + '" data-type="' + (s.type || 'text') + '">'
      + '<div class="row-label">' + s.label + '</div>'
      + '<div class="rv">' + disp + '</div>'
      + '</div>';
  }
  return '<div class="row" data-key="' + (s.key || '') + '" data-type="' + (s.type || 'text') + '">'
    + '<div class="row-label">' + s.label + '</div>'
    + '<div class="rv">' + disp + '</div>'
    + '<div class="ri" hidden><div style="display:flex;align-items:center">' + buildInput(s, val) + note + '</div></div>'
    + '<button class="be" onclick="startEdit(this)" title="Edit">&#9998;</button>'
    + '<button class="bs hidden" onclick="doSave(this)" title="Save">&#10003;</button>'
    + '<button class="bc hidden" onclick="doCancel(this)" title="Cancel">&#10005;</button>'
    + '</div>';
}

function buildPage(SCHEMA, endpoint) {
  fetch(endpoint)
    .then(function(r) { return r.json(); })
    .then(function(d) {
      var html = '';
      SCHEMA.forEach(function(s) {
        if (s.section) {
          html += '<div class="section-label">' + s.section + '</div>';
          return;
        }
        var val = (d[s.key] !== undefined) ? String(d[s.key]) : '?';
        html += buildRow(s, val);
      });
      document.querySelector('main').innerHTML = html;
    })
    .catch(function() {
      var el = document.getElementById('status');
      if (el) el.textContent = 'Failed to load settings.';
    });
}
</script>
<script>
var SCHEMA = [
  {section:'Radio'},
  {key:'rcchn', label:'Channel Count',       type:'number', min:6,   max:8},
  {key:'rcd',   label:'Deadzone',            type:'number', min:1,   max:50},
  {key:'rcj',   label:'Jitter Filter',       type:'number', min:1,   max:40},
  {key:'fst',   label:'Failsafe Timeout',    type:'number', min:1000,max:3000, note:'ms'},
  {section:'Right Joystick Calibration'},
  {key:'rvrmin',label:'Min Reference',       type:'number', min:0,   max:100},
  {key:'rvrmax',label:'Max Reference',       type:'number', min:900, max:1023},
  {section:'Left Joystick Calibration'},
  {key:'rvlmin',label:'Min Reference',       type:'number', min:0,   max:100},
  {key:'rvlmax',label:'Max Reference',       type:'number', min:900, max:1023},
  {section:'Joystick Adjustment'},
  {key:'j1adjv',label:'Vertical Adjust',     type:'number', min:0,   max:80},
  {key:'j1adjh',label:'Horizontal Adjust',   type:'number', min:0,   max:80}
];
buildPage(SCHEMA, '/api/config/rc-radio');
</script>
</body>
</html>
)html";

static const char WEB_PAGE_DOME[] = R"html(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Dome Drive — AMIDALA</title>
<style>
/* Amidala web UI — shared styles.
   Embed script inlines this into every page's <style> block.
   In dev mode (scripts/web_dev.py) it's served as a real file from /assets/common.css. */

*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

:root {
  --gold:   #ffe81f;
  --red:    #c00;
  --bg:     #000;
  --card:   #0a0a0a;
  --dim:    #555;
  --border: #ffe81f22;
}

body {
  background: var(--bg);
  color: var(--gold);
  font-family: 'Courier New', Courier, monospace;
  min-height: 100vh;
  font-size: 15px;
}

a {
  color: var(--gold);
  text-decoration: none;
}

button {
  cursor: pointer;
  font-family: inherit;
}

.hidden {
  display: none !important;
}

.toast {
  position: fixed;
  bottom: 1.5rem;
  left: 50%;
  transform: translateX(-50%);
  background: #111;
  border: 1px solid var(--gold);
  color: var(--gold);
  padding: .55rem 1.4rem;
  font-size: .78rem;
  letter-spacing: .08em;
  pointer-events: none;
  white-space: nowrap;
  animation: _tfi .15s ease, _tfo .3s 1.9s ease forwards;
  z-index: 9999;
}
.toast-err {
  border-color: var(--red);
  color: var(--red);
}
@keyframes _tfi {
  from { opacity: 0; transform: translateX(-50%) translateY(6px) }
  to   { opacity: 1; transform: translateX(-50%) translateY(0) }
}
@keyframes _tfo {
  from { opacity: 1 }
  to   { opacity: 0 }
}
</style>
<style>
.page-header{display:flex;align-items:center;padding:.9rem 1rem;border-bottom:1px solid var(--border);gap:1rem}
.back{font-size:.8rem;color:var(--dim);letter-spacing:.1em;white-space:nowrap}
.back:hover{color:var(--gold)}
.page-title{flex:1;text-align:center;font-size:.9rem;letter-spacing:.25em;text-transform:uppercase}
main{max-width:660px;margin:0 auto;padding:1rem}
.section-label{font-size:.6rem;color:var(--dim);letter-spacing:.25em;text-transform:uppercase;padding:.5rem 0 .4rem;border-bottom:1px solid var(--border);margin-bottom:.2rem}
.row{display:flex;align-items:center;padding:.7rem .2rem;border-bottom:1px solid #0f0f0f;gap:.5rem}
.row-label{flex:1;font-size:.82rem;color:#ccc}
.rv{font-size:.82rem;color:var(--gold);min-width:60px;text-align:right}
.ri{min-width:90px}
.ri input,.ri select{width:100%;background:#111;border:1px solid var(--dim);color:var(--gold);padding:.3rem .5rem;font-family:inherit;font-size:.82rem}
.ri select option{background:#111}
.be,.bs,.bc{background:none;border:none;color:var(--gold);font-size:1rem;padding:.2rem .5rem;opacity:.6}
.be:hover,.bs:hover,.bc:hover{opacity:1}
.bc{color:var(--dim)}
#status{text-align:center;padding:2rem;color:var(--dim);font-size:.8rem;letter-spacing:.1em}
</style>
</head>
<body>
<div class="page-header">
  <a class="back" href="/">&#9664; Back</a>
  <div class="page-title">&#9670; Dome Drive &#9670;</div>
</div>
<main>
  <div id="status">LOADING&#8230;</div>
</main>
<script>
/* Amidala web UI — edit-in-place widget + shared config page helpers.
   Embed script inlines this into every config sub-page.
   In dev mode (scripts/web_dev.py) it's served as /assets/edit.js. */

// ------------------------------------------------------------------ toast ---

function showToast(msg, isErr) {
  var t = document.createElement('div');
  t.className = 'toast' + (isErr ? ' toast-err' : '');
  t.textContent = msg;
  document.body.appendChild(t);
  setTimeout(function() { if (t.parentNode) t.parentNode.removeChild(t); }, 2200);
}

// -------------------------------------------------------- edit-in-place -----

function startEdit(btn) {
  var row = btn.closest('.row');
  row.querySelector('.rv').hidden = true;
  row.querySelector('.ri').hidden = false;
  btn.hidden = true;
  row.querySelector('.bs').hidden = false;
  row.querySelector('.bc').hidden = false;
}

function doCancel(btn) {
  var row = btn.closest('.row');
  row.querySelector('.rv').hidden = false;
  row.querySelector('.ri').hidden = true;
  row.querySelector('.be').hidden = false;
  row.querySelector('.bs').hidden = true;
  btn.hidden = true;
}

async function doSave(btn) {
  var row = btn.closest('.row');
  var key = row.dataset.key;
  var inp = row.querySelector('input,select');
  var val = inp.value;
  var prev = btn.textContent;
  btn.textContent = '...';
  btn.disabled = true;
  try {
    var r = await fetch('/api/config', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: 'key=' + encodeURIComponent(key) + '&value=' + encodeURIComponent(val)
    });
    if (r.ok) {
      var dv = row.querySelector('.rv');
      var rt = row.dataset.type;
      if (rt === 'bool' || rt === 'select') {
        var sel = row.querySelector('select');
        dv.textContent = sel.options[sel.selectedIndex].text;
      } else if (rt === 'password') {
        dv.textContent = '••••••••';
      } else {
        dv.textContent = val;
      }
      doCancel(row.querySelector('.bc'));
      showToast('Saved');
    } else {
      showToast('Save failed: ' + await r.text(), true);
    }
  } catch(e) {
    showToast('Network error', true);
  }
  btn.textContent = prev;
  btn.disabled = false;
}

// ------------------------------------------------ schema-driven row builder --

function dispValue(s, val) {
  if (s.type === 'bool') return val === 'y' ? 'On' : 'Off';
  if (s.type === 'select') {
    var found = (s.options || []).find(function(op) { return op.v === String(val); });
    return found ? found.l : val;
  }
  if (s.type === 'password') return '••••••••';
  return String(val);
}

function buildInput(s, val) {
  if (s.type === 'bool') {
    return '<select>'
      + '<option value="y"' + (val === 'y' ? ' selected' : '') + '>On</option>'
      + '<option value="n"' + (val === 'n' ? ' selected' : '') + '>Off</option>'
      + '</select>';
  }
  if (s.type === 'select') {
    var opts = (s.options || []).map(function(op) {
      return '<option value="' + op.v + '"' + (String(val) === op.v ? ' selected' : '') + '>' + op.l + '</option>';
    }).join('');
    return '<select>' + opts + '</select>';
  }
  if (s.type === 'number') {
    return '<input type="number" value="' + val + '" min="' + (s.min || 0) + '" max="' + (s.max || 9999) + '">';
  }
  if (s.type === 'password') {
    return '<input type="password" value="' + val + '" maxlength="' + (s.maxlength || 64) + '">';
  }
  return '<input type="text" value="' + val + '"' + (s.maxlength ? ' maxlength="' + s.maxlength + '"' : '') + '>';
}

function buildRow(s, val) {
  var disp = dispValue(s, val);
  var note = s.note ? '<span style="font-size:.65rem;color:var(--dim);margin-left:.3rem">' + s.note + '</span>' : '';
  if (s.readOnly) {
    return '<div class="row" data-key="' + (s.key || '') + '" data-type="' + (s.type || 'text') + '">'
      + '<div class="row-label">' + s.label + '</div>'
      + '<div class="rv">' + disp + '</div>'
      + '</div>';
  }
  return '<div class="row" data-key="' + (s.key || '') + '" data-type="' + (s.type || 'text') + '">'
    + '<div class="row-label">' + s.label + '</div>'
    + '<div class="rv">' + disp + '</div>'
    + '<div class="ri" hidden><div style="display:flex;align-items:center">' + buildInput(s, val) + note + '</div></div>'
    + '<button class="be" onclick="startEdit(this)" title="Edit">&#9998;</button>'
    + '<button class="bs hidden" onclick="doSave(this)" title="Save">&#10003;</button>'
    + '<button class="bc hidden" onclick="doCancel(this)" title="Cancel">&#10005;</button>'
    + '</div>';
}

function buildPage(SCHEMA, endpoint) {
  fetch(endpoint)
    .then(function(r) { return r.json(); })
    .then(function(d) {
      var html = '';
      SCHEMA.forEach(function(s) {
        if (s.section) {
          html += '<div class="section-label">' + s.section + '</div>';
          return;
        }
        var val = (d[s.key] !== undefined) ? String(d[s.key]) : '?';
        html += buildRow(s, val);
      });
      document.querySelector('main').innerHTML = html;
    })
    .catch(function() {
      var el = document.getElementById('status');
      if (el) el.textContent = 'Failed to load settings.';
    });
}
</script>
<script>
var SCHEMA = [
  {section:'Speed'},
  {key:'domespeed',     label:'Max Speed',         type:'number', min:0,  max:100},
  {key:'domespeedhome', label:'Home Speed',         type:'number', min:1,  max:100},
  {key:'domespeedseek', label:'Seek Speed',         type:'number', min:1,  max:100},
  {key:'domespeedmin',  label:'Min Speed',          type:'number', min:0,  max:30},
  {key:'domedecelzone', label:'Decel Zone',         type:'number', min:5,  max:90, note:'degrees'},
  {section:'Position'},
  {key:'domehome',  label:'Home Position',          type:'number', min:0,  max:360, note:'degrees'},
  {key:'domeflip',  label:'Invert Direction',       type:'bool'},
  {key:'domeimu',   label:'IMU Assist',             type:'bool'},
  {key:'domech6',   label:'Channel 6 Mode',         type:'bool'},
  {section:'Seek Range'},
  {key:'domeseekl', label:'Left Seek',              type:'number', min:1,  max:180, note:'degrees'},
  {key:'domeseekr', label:'Right Seek',             type:'number', min:1,  max:180, note:'degrees'},
  {key:'domefudge', label:'Position Fudge',         type:'number', min:1,  max:45,  note:'degrees'},
  {section:'RoboClaw'},
  {key:'domercaddr',label:'Packet Address',         type:'number', min:128,max:135},
  {key:'domercchan',label:'Motor Channel',          type:'select', options:[{v:'1',l:'M1'},{v:'2',l:'M2'}]},
  {key:'domercqpps',label:'QPPS',                  type:'number', min:1,  max:65535, note:'ticks/sec at max speed'},
  {key:'domefront', label:'Front Offset',           type:'number', min:0,  max:359, note:'degrees'},
  {key:'domestall', label:'Stall Timeout',          type:'number', min:100,max:5000, note:'ms'}
];
buildPage(SCHEMA, '/api/config/dome');
</script>
</body>
</html>
)html";

static const char WEB_PAGE_COMING_SOON[] = R"html(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>AMIDALA</title>
<style>
/* Amidala web UI — shared styles.
   Embed script inlines this into every page's <style> block.
   In dev mode (scripts/web_dev.py) it's served as a real file from /assets/common.css. */

*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

:root {
  --gold:   #ffe81f;
  --red:    #c00;
  --bg:     #000;
  --card:   #0a0a0a;
  --dim:    #555;
  --border: #ffe81f22;
}

body {
  background: var(--bg);
  color: var(--gold);
  font-family: 'Courier New', Courier, monospace;
  min-height: 100vh;
  font-size: 15px;
}

a {
  color: var(--gold);
  text-decoration: none;
}

button {
  cursor: pointer;
  font-family: inherit;
}

.hidden {
  display: none !important;
}

.toast {
  position: fixed;
  bottom: 1.5rem;
  left: 50%;
  transform: translateX(-50%);
  background: #111;
  border: 1px solid var(--gold);
  color: var(--gold);
  padding: .55rem 1.4rem;
  font-size: .78rem;
  letter-spacing: .08em;
  pointer-events: none;
  white-space: nowrap;
  animation: _tfi .15s ease, _tfo .3s 1.9s ease forwards;
  z-index: 9999;
}
.toast-err {
  border-color: var(--red);
  color: var(--red);
}
@keyframes _tfi {
  from { opacity: 0; transform: translateX(-50%) translateY(6px) }
  to   { opacity: 1; transform: translateX(-50%) translateY(0) }
}
@keyframes _tfo {
  from { opacity: 1 }
  to   { opacity: 0 }
}
</style>
<style>
body{display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:100vh;text-align:center;gap:1rem}
.big{font-size:3rem}
p{color:var(--dim);font-size:.8rem;letter-spacing:.15em}
a{color:var(--dim);font-size:.75rem;letter-spacing:.1em;margin-top:1rem;display:block}
a:hover{color:var(--gold)}
</style>
</head>
<body>
<div class="big">&#9670;</div>
<p>COMING SOON</p>
<a href="/">&#9664; BACK TO HOME</a>
</body>
</html>
)html";
